name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Debug
      run: |
        pwd
        echo ${GOPATH}
        echo ${GOROOT}

    - name: Build
      run: chmod +x build.sh && ./build.sh com/katalon/katalonwrapper
      env: 
        GOPATH: /home/runner/work/katalon-wrapper/katalon-wrapper
