name: Katalon Wrapper
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: chmod +x build.sh && ./build.sh com/katalon/katalonwrapper
      env: 
        GOPATH: /home/runner/work/katalon-wrapper/katalon-wrapper

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: katalon-wrapper
        path: bin
